publish report

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -15,10 +15,16 @@ jobs:
       run: npm run test:unit
     - name: Run unit test:cov
       run: npm run unit-test:cov
+    - name: Publish Unit-Test Report
+      uses: mikepenz/action-junit-report@v3
+      if: success() || failure() # always run even if the previous step fails
+      with:
+        report_paths: 'unit-test-result/*.xml'
     - name: Build and push Docker image
       uses: docker/build-push-action@v2
       with:
         context: .
         push: false
         tags: ${{ env.IMAGE_NAME }}:${{ github.sha }}
+
       
